<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>

		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">
			$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst
		</TargetFrameworks>

		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">
			$(TargetFrameworks);net10.0-windows10.0.19041.0
		</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>CeramicManager</RootNamespace>

		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<MauiXamlInflator>SourceGen</MauiXamlInflator>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>

		<ApplicationTitle>CeramicManager</ApplicationTitle>
		<ApplicationId>com.companyname.ceramicmanager</ApplicationId>

		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- Windows بدون MSIX -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
			15.0
		</SupportedOSPlatformVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
			15.0
		</SupportedOSPlatformVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
			21.0
		</SupportedOSPlatformVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
			10.0.17763.0
		</SupportedOSPlatformVersion>

		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
			10.0.17763.0
		</TargetPlatformMinVersion>
	</PropertyGroup>

	<!-- Android -->
	<PropertyGroup Condition="'$(Configuration)' == 'Release' AND '$(TargetFramework)' == 'net10.0-android'">
		<RuntimeIdentifier>android-arm64</RuntimeIdentifier>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
		<EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	</PropertyGroup>

	<!-- Windows Release -->
	<PropertyGroup Condition="'$(Configuration)' == 'Release' AND '$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg"
				  ForegroundFile="Resources\AppIcon\appiconfg.svg"
				  Color="#17171a" />

		<MauiSplashScreen Include="Resources\Splash\splash.svg"
						  Color="#17171a"
						  BaseSize="128,128" />

		<MauiImage Include="Resources\Images\*" />

		<MauiFont Include="Resources\Fonts\*" />

		<MauiAsset Include="Resources\Raw\**"
				   LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="CommunityToolkit.Maui" Version="12.3.0" />
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.8" />
		<PackageReference Include="QuestPDF" Version="2026.8.0" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.10" />
		<PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.8" />
	</ItemGroup>

</Project>