workflows:
  maui-ios-build:
    name: CeramicManager iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
    scripts:
      - name: Install .NET SDK
        script: |
          # تحميل وتثبيت سكريبت دوت نت الرسمي
          curl -sSL https://dot.net -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version 9.0.100 --install-dir $HOME/dotnet
          
          # إضافة دوت نت إلى مسار النظام المؤقت داخل الخادم ليتعرف عليه
          echo "export DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV
          echo "export PATH=$PATH:$HOME/dotnet" >> $GITHUB_ENV
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$PATH:$HOME/dotnet

      - name: Build iOS Application
        script: |
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$PATH:$HOME/dotnet
          dotnet workload install maui
          dotnet build CeramicManager.csproj -c Release -f net9.0-ios
    artifacts:
      - $CM_BUILD_DIR/**/*.ipa
